export const DRAGON_ROUTER_RESPONSE_HEADERS = {
  cache: "X-Dragon Router-Cache",
  cacheHit: "X-Dragon Router-Cache-Hit",
  compression: "X-Dragon Router-Compression",
  costSaved: "X-Dragon Router-Cost-Saved",
  fallbackAttempts: "X-Dragon Router-Fallback-Attempts",
  latencyMs: "X-Dragon Router-Latency-Ms",
  model: "X-Dragon Router-Model",
  progress: "X-Dragon Router-Progress",
  provider: "X-Dragon Router-Provider",
  requestId: "X-Dragon Router-Request-Id",
  responseCost: "X-Dragon Router-Response-Cost",
  tokensIn: "X-Dragon Router-Tokens-In",
  tokensOut: "X-Dragon Router-Tokens-Out",
  version: "X-Dragon Router-Version",
} as const;
